routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function (){
    return Redirect::to('/home');
});

Route::prefix('dashboard')->group(function () {
    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
});
Route::namespace('Admin')
->prefix('dashboard')
->middleware('auth')
->group(function () {
    Route::resource('organizers', OrganizerController::class);
    Route::resource('data-entry', DataEntryController::class);
    Route::resource('users', UserController::class);
    Route::resource('palyers', PlayerController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('news', NewsController::class);

    Route::resource('events', EventController::class);
    Route::get('show_teams/{event_id}', 'EventController@showTeams')->name('event.show.team');
    Route::post('add_teams', 'EventController@addTeams')->name('event.add.team');

    Route::resource('teams', TeamController::class);
    Route::get('show_players/{team_id}', 'TeamController@showPlayers')->name('team.show.player');
    Route::post('add_players', 'TeamController@addPlayers')->name('team.add.player');

});

Route::namespace('Website')
->group(function () {

    Route::get('{slug}', PageController::class);
    Route::get('show_event/{id}', 'PageController@eventCategoryPage')->name('event.category.page');
    Route::get('show_news/{id}', 'PageController@showNews')->name('show.news.detail.page');

    Route::post('/new/register', PublicRegisterController::class)->name('website.post');
    Route::post('/new/Login', PublicLoginController::class)->name('website.login');

});

// clientdashboard and organizer
// Route::group(['middleware' => 'auth'],function () {
//     Route::get('/userdashboard', function () {
//         return view('website.clientDashboard.index');
//     })->name('userdashboard');

// });
Route::namespace('ClientDashboard')
 ->middleware(['auth'])
 ->as('userdashboard.')
 ->prefix('userdashboard')
 ->group(function(){
     Route::get('/home', HomeController::class)->name('home');
 });

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'organizer_id','category_id','event_name','avtar','date','time','location','description'
    ];

    public function category()
    {
        return $this->hasOne(Categories::class, 'id', 'category_id');
    }

}

app/Http/Controllers/Admin/EventController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\FileUploadService;
use App\EventHaveTeam;
use App\Categories;
use App\Event;
use App\Team;
use Auth;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::latest()->get();
        return view('admin.event.index', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categories::latest()->get();
        return view('admin.event.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // 'avtar '  => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048|required',

     $validateData = $request->validate([
        'event_name' => 'required',
        'time' => 'required',
        'location' => 'required',
        'description' => 'required',
        'category_id' => 'required',
     ]);

    //  $file = FileUploadService::upload( $request->file('avtar'), 'public/profile/' );

     $event = new Event;
     $event->organizer_id = Auth::user()->id;
     $event->category_id = $request->category_id;
     $event->event_name = $request->event_name;
     $event->date  = $request->date;
     $event->avtar ='dumy';
     $event->time = $request->time;
     $event->location = $request->location;
     $event->description = $request->description;

     $event->save();


     $request->session()->flash('msg','Record successfully inserted');
     return redirect()->route('events.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event=Event::find($id);
        return view('admin.event.show',compact('event'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::find($id);
        $categories = Categories::latest()->get();

        return view('admin.event.edit',['event'=>$event,'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validateData = $request->validate([
            'event_name' => 'required',
            'time' => 'required',
            'location' => 'required',
            'description' => 'required',
            'category_id' => 'required',
         ]);



         $event =Event::find($id);
         $event->organizer_id = Auth::user()->id;
         $event->category_id = $request->category_id;
         $event->event_name = $request->event_name;
         $event->date  = $request->date;
         $event->avtar ='dumy';
         $event->time = $request->time;
         $event->location = $request->location;
         $event->description = $request->description;

         $event->save();


         $request->session()->flash('msg','Record successfully inserted');
         return redirect()->route('events.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $data = EventHaveTeam::where('event_id', $id)->get();
        if($data !== null){
            foreach ($data as $key => $event) {
                # code...
                $d = EventHaveTeam::where('id', $event->id)->first();
                $d->delete();
            }
        }

        $event=Event::find($id);
        $event->delete();
        if ($event != null){
            $event->delete();
            session()->flash('msg','User Deleted Successfully');
        }

        return back();
    }

    public function showTeams($event_id){


        $event = Event::find($event_id);
        $getExistingTeams = EventHaveTeam::where('event_id', $event_id)->get()->pluck('team_id')->toArray();
        $teams = Team::where('organizer_id', Auth::user()->id)->whereNotIn('id', $getExistingTeams)->latest()->get();
        return view('admin.event.selectTeam',compact('event', 'teams'));

    }

    public function addTeams(Request $request){

        $validateData = $request->validate([
            'event_id' => 'required',
            'team' => 'required',
         ]);

         foreach ($_POST['team'] as $key => $value) {
            # code...
            $teamplayer = new EventHaveTeam;
            $teamplayer->event_id = $request->event_id;
            $teamplayer->team_id = $value;
            $teamplayer->save();

        }

        return back();

    }

}

resources/views/admin/event/create.blade.php
@extends("layouts.admin.site")
@section("content")
<h4 class="font-weight-bold py-3 mb-4">
    Add Event <span class="text-muted"></span>
</h4>

<div class="nav-tabs-top">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#user-edit-account">Account</a>
        </li>

    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="user-edit-account">
            <form action="{{ route('events.store') }}" method="POST" enctype="multipart/form-data">

                @csrf

                <div class="card-body">

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    {{-- <div class="media align-items-center">
                        <img src="{{ asset('assets/images/client-01.png') }}" id="change-avatar" alt="" class="d-block ui-w-80">
                        <div class="media-body ml-3">
                            <label class="form-label d-block mb-2">Avatar</label>
                            <label class="btn btn-outline-primary btn-sm">
                                Add
                                <input type="file" name="avtar"   onchange="changeAvatar(this);" class="user-edit-fileinput d-none">
                                </label>&nbsp;
                        </div>
                    </div> --}}

                </div>
                <hr class="border-light m-0">
                <div class="card-body pb-2">

                    <div class="form-group">
                        <label class="form-label">Event Name</label>
                        <input type="text" name="event_name" class="form-control mb-1" placeholder="Event Name">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Event Category</label>
                        <select name="category_id" class="custom-select">
                          <option selected disabled hidden>Select Category</option>
                          @isset($categories)
                              @foreach ($categories as $category)
                                <option  value="{{ $category->id ?? '' }}">{{ $category->category_name ?? '' }}</option>
                              @endforeach
                          @endisset
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Location</label>
                        <input type="text" name="location" class="form-control mb-1" placeholder="Location">
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="form-label">Date</label>
                            <input type="date" name="date" class="form-control" placeholder="Date">
                        </div>
                        <div class="form-group col-md-6">
                            <label class="form-label">Time</label>
                            <input type="time" name="time" class="form-control" placeholder="Date">
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="form-label">Description</label>
                        <textarea name="description" id="" class="form-control" cols="30" rows="10"></textarea>
                    </div>
                </div>
                <div class="text-right mt-3">
                    <button type="submit" class="btn btn-primary">Add </button>&nbsp;
                </div>
            </form>


        </div>
    </div>
</div>
<script>
    function changeAvatar(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
              $('#change-avatar')
                  .attr('src', e.target.result)
                  .width(80)
                  .height(80);
          };
          reader.readAsDataURL(input.files[0]);
      }
  }
</script>
@endsection

resources/views/admin/event/edit.blade.php
@extends("layouts.admin.site")
@section("content")
<h4 class="font-weight-bold py-3 mb-4">
    Edit Event <span class="text-muted"></span>
</h4>

<div class="nav-tabs-top">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#user-edit-account">Account</a>
        </li>

    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="user-edit-account">
            <form method="POST" action="{{route('events.update',$event->id)}}">
                @csrf
                @method('put')

                <div class="card-body">

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="card-body">
{{--
                    <div class="media align-items-center">
                        <img src="assets/img/avatars/5-small.png" alt="" class="d-block ui-w-80">
                        <div class="media-body ml-3">
                            <label class="form-label d-block mb-2">Avatar</label>
                            <label class="btn btn-outline-primary btn-sm">
      Add
      <input type="file" class="user-edit-fileinput">
    </label>&nbsp;

                        </div>
                    </div> --}}

                </div>
                <hr class="border-light m-0">
                <div class="card-body pb-2">

                    <div class="form-group">
                        <label class="form-label">Event Name</label>
                        <input type="text" name="event_name" class="form-control mb-1" value="{{ $event->event_name }}" placeholder="Event Name">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Event Category</label>
                        <select name="category_id" class="custom-select">
                          <option selected disabled hidden>{{ $event->category->category_name ?? '' }}</option>
                          @isset($categories)
                              @foreach ($categories as $category)
                                <option  value="{{ $category->id ?? '' }}">{{ $category->category_name ?? '' }}</option>
                              @endforeach
                          @endisset
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Location</label>
                        <input type="text" name="location" class="form-control mb-1" value="{{ $event->location }}" placeholder="Location">
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="form-label">Date</label>
                            <input type="date" name="date" value="{{ $event->date }}" class="form-control placeholder="Date">
                        </div>
                        <div class="form-group col-md-6">
                            <label class="form-label">Time</label>
                            <input type="time" name="time" class="form-control" value="{{ $event->time }}" placeholder="Date">
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="form-label">Description</label>
                        <textarea name="description" id="" class="form-control" cols="30" rows="10" >{{ $event->description }}</textarea>
                    </div>
                </div>
                <div class="text-right mt-3">
                    <button type="submit" class="btn btn-primary">Save changes</button>&nbsp;
                    {{-- <button type="button" class="btn btn-default">Cancel</button> --}}
                </div>
            </form>


        </div>
    </div>
</div>
@endsection

resources/views/admin/event/eventConfirm.blade.php
@extends('layouts.admin.site')
@section('content')
<h4 class="font-weight-bold py-3 mb-4">
    <span class="text-muted font-weight-light">event </span>
</h4>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('msg') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
 </div>
<!-- DataTable within card -->

<div class="card">
    <h6 class="card-header">
        <h6 class="card-header text-right">
            <a href="{{ route('events.create') }}" class="btn btn-success" > Add New</a>
        </h6>
    </h6>
    <div class="card-datatable table-responsive">
        <table class="datatables-demo table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Event Name</th>
                    <th>Location</th>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @isset($events)
                    @if (count($events) > 0)
                        @foreach ($events as $event)
                        <tr class="odd gradeX">
                            <td>{{ $event->id ?? '' }}</td>
                            <td>{{ $event->event_name ?? '' }}</td>
                            <td>{{ $event->category->category_name ?? '' }}</td>
                            <td>{{ $event->date ?? '' }} {{ $event->time ?? '' }}</td>
                            <td>{{ $event->location ?? '' }}</td>
                            <td>{{ $event->description ?? '' }}</td>

                            <td class="text-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-success dropdown-toggle waves-effect" data-toggle="dropdown" aria-expanded="false">Done</button>
                                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: top, left; top: 25px; left: 0px;">
                                        <a class="dropdown-item">undone</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @else
                        <div class="m-3 text-center col-12">
                            <p>No Players found...!</p>
                        </div>
                    @endif
                @endisset


            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/admin/event/index.blade.php
@extends('layouts.admin.site')
@section('content')
<h4 class="font-weight-bold py-3 mb-4">
    <span class="text-muted font-weight-light">event </span>
</h4>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('msg') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
 </div>
<!-- DataTable within card -->

<div class="card">
    <h6 class="card-header">
        <h6 class="card-header text-right">
            <a href="{{ route('events.create') }}" class="btn btn-success" > Add New</a>
        </h6>

    </h6>
    <div class="card-datatable table-responsive">
        <table class="datatables-demo table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Date Time</th>
                    <th>Location</th>
                    <th>Confirm</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @isset($events)
                    @if (count($events) > 0)
                        @foreach ($events as $event)
                        <tr class="odd gradeX">
                            <td>{{ $event->id ?? '' }}</td>
                            <td>{{ $event->event_name ?? '' }}</td>
                            <td>{{ $event->category->category_name ?? '' }}</td>
                            <td>{{ $event->date ?? '' }} {{ $event->time ?? '' }}</td>
                            <td>{{ $event->location ?? '' }}</td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-success dropdown-toggle waves-effect" data-toggle="dropdown" aria-expanded="false">Confirmed</button>
                                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: top, left; top: 25px; left: 0px;">
                                        <a class="dropdown-item">unconfirmed</a>
                                    </div>
                                </div>
                            </td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-dark dropdown-toggle waves-effect" data-toggle="dropdown" aria-expanded="false">Action</button>
                                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: top, left; top: 35px; left: 0px;">
                                        <a href="{{ route('events.show',$event->id) }}" class="dropdown-item"><i class="fa fa-eye"></i> View Event Detail</a>

                                        <a href="{{ route('event.show.team', $event->id) }}" class="dropdown-item"><i class="fa fa-plus"></i> Add Team </a>

                                        <a href="{{ route('events.edit', $event->id) }}" class="dropdown-item"><i class="fa fa-edit"></i> Edit </a>
                                        <form action="{{ route('events.destroy',$event->id) }}" class="d-flex" method="post">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE"> <button class="dropdown-item">
                                    <i class="fa fa-trash"></i> Delete
                                  </button>
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @else
                        <div class="m-3 text-center col-12">
                            <p>No Players found...!</p>
                        </div>
                    @endif
                @endisset


            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/admin/event/selectTeam.blade.php
@extends('layouts.admin.site')
@section('content')
<h4 class="font-weight-bold py-3 mb-4">
    <span class="text-muted font-weight-light">Teams </span>
</h4>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('msg') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
 </div>
<!-- DataTable within card -->

<div class="card">

        <h6 class="card-header text-right">
            <a href="#" class="btn btn-success" > Add New team</a>
        </h6>

    <div class="all team">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('event.add.team') }}" method="post">

            @csrf

            <input type="hidden" name="event_id" value="{{ $event->id ?? ''}}">

            @isset($teams)
                @if (count($teams) > 0)
                    @foreach ($teams as $team)
                        <div class="form-check border-bottom p-3 pl-5">
                            <input class="form-check-input" name="team[]" type="checkbox" value="{{ $team->id ?? '' }}">
                            <label class="form-check-label" for="defaultCheck1">
                                {{ $team->team_name ?? '' }}
                            </label>
                        </div>
                    @endforeach
                @else
                    <p>No team Found</p>
                @endif
            @endisset

            <div class="text-right mt-3 mb-3 mr-3">
                <button type="submit" class="btn btn-primary">Add Team</button>&nbsp;
                {{-- <button type="button" class="btn btn-default">Cancel</button> --}}
            </div>

    </form>

    </div>
</div>
@endsection

resources/views/admin/event/show.blade.php
@extends("layouts.admin.site")
@section("content")
<div class="media align-items-center py-3 mb-3">
    <img src="assets/img/avatars/5-small.png" alt="" class="d-block ui-w-100 rounded-circle">
    <div class="media-body ml-4">
        {{-- <h4 class="font-weight-bold mb-0">Nelle Maxwell <span class="text-muted font-weight-normal">@nmaxwell</span></h4> --}}
        {{-- <div class="text-muted mb-2">ID: 3425433</div> --}}
        <a href="javascript:void(0)" class="btn btn-primary btn-sm">Edit</a>&nbsp;
        <a href="javascript:void(0)" class="btn btn-default btn-sm">Profile</a>&nbsp;
        <a href="javascript:void(0)" class="btn btn-default btn-sm icon-btn"><i class="ion ion-md-mail"></i></a>
    </div>
</div>


<div class="card">

    <div class="card-body">

        <table class="table user-view-table m-0">
            <tbody>

                <tr>
                    <td>Event Name:</td>
                    <td>{{ $event->event_name }}</td>
                </tr>
                <tr>
                    <td>Date</td>
                    <td>{{ $event->date }}</td>
                </tr>
                <tr>
                    <td>Location:</td>
                    <td>{{ $event->location }}</td>
                </tr>

                <tr>
                    <td>About:</td>
                    <td>{{ $event->description }}</td>
                </tr>
            </tbody>
        </table>

    </div>
</div>
@endsection